CREATE MATERIALIZED VIEW  "ATAF_APEX_PAGE_ITEMS_MV" ("APPLICATION_ID", "PAGE_ID", "LABEL", "TYPE", "DOM_ID", "NAME", "DISPLAY_SEQUENCE", "ID", "ELEMENT_TYPE", "REGION_ID", "REGION_NAME", "DISPLAY_SEQUENCE1", "DISPLAY_SEQUENCE2")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 60 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 57344 NEXT 57344 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT TRUNC(SYSDATE+1)
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select 
  APPLICATION_ID,
  PAGE_ID,
  LABEL,
  TYPE,
  DOM_ID,
  NAME,
  DISPLAY_SEQUENCE,
  ID,
  ELEMENT_TYPE,
  REGION_ID,
  REGION_NAME,
  DISPLAY_SEQUENCE1,
  DISPLAY_SEQUENCE2
from ATAF_APEX_PAGE_ITEMS_V
  where display = 'Y'
/