REM INSERTING into ATAF.ATAF_MODULE
SET DEFINE OFF;
Insert into ATAF.ATAF_MODULE (MODULE_ID,MODULE,PROJECT_ID,MODULE_REF_ID,LAST_UPDATED_DATE,LAST_UPDATED_BY) values (9715,'General',9714,null,to_date('07-MAR-2017','DD-MON-RRRR'),'ATAF');
Insert into ATAF.ATAF_MODULE (MODULE_ID,MODULE,PROJECT_ID,MODULE_REF_ID,LAST_UPDATED_DATE,LAST_UPDATED_BY) values (9719,'Actions',9714,null,to_date('07-MAR-2017','DD-MON-RRRR'),'ATAF');
Insert into ATAF.ATAF_MODULE (MODULE_ID,MODULE,PROJECT_ID,MODULE_REF_ID,LAST_UPDATED_DATE,LAST_UPDATED_BY) values (9717,'Projects',9714,null,to_date('07-MAR-2017','DD-MON-RRRR'),'ATAF');
Insert into ATAF.ATAF_MODULE (MODULE_ID,MODULE,PROJECT_ID,MODULE_REF_ID,LAST_UPDATED_DATE,LAST_UPDATED_BY) values (9723,'Custom Items',9714,null,to_date('07-MAR-2017','DD-MON-RRRR'),'ATAF');
Insert into ATAF.ATAF_MODULE (MODULE_ID,MODULE,PROJECT_ID,MODULE_REF_ID,LAST_UPDATED_DATE,LAST_UPDATED_BY) values (9721,'Test Data',9714,null,to_date('07-MAR-2017','DD-MON-RRRR'),'ATAF');
