REM INSERTING into ATAF.ATAF_ITEM
SET DEFINE OFF;
Insert into ATAF.ATAF_ITEM (ITEM_ID,ITEM_NAME,ITEM_DOM_ID,PAGE_ID,DISPLAY_SEQUENCE,ITEM_LABEL,APPLICATION_ID,LAST_UPDATED_DATE,LAST_UPDATED_BY,ITEM_TYPE,REGION_NAME) values (640008674,'Test',null,0,null,'Test',242,to_date('10-MAR-2017','DD-MON-RRRR'),'ADMIN_USER','Custom','test');
