REM INSERTING into ATAF.ATAF_TEST_SPEC
SET DEFINE OFF;
Insert into ATAF.ATAF_TEST_SPEC (TEST_SPEC_ID,TEST_SPEC,TEST_TYPE,PROJECT_ID,AUTOMATE,SORT_ORDER,LAST_UPDATED_DATE,LAST_UPDATED_BY,NOTES,MODULE_ID) values (9716,'Smoke Test','Smoke',9714,'Y',10,to_date('07-MAR-2017','DD-MON-RRRR'),'ATAF',null,9715);
Insert into ATAF.ATAF_TEST_SPEC (TEST_SPEC_ID,TEST_SPEC,TEST_TYPE,PROJECT_ID,AUTOMATE,SORT_ORDER,LAST_UPDATED_DATE,LAST_UPDATED_BY,NOTES,MODULE_ID) values (9718,'Manage Projects','Function',9714,'Y',20,to_date('07-MAR-2017','DD-MON-RRRR'),'ATAF',null,9717);
Insert into ATAF.ATAF_TEST_SPEC (TEST_SPEC_ID,TEST_SPEC,TEST_TYPE,PROJECT_ID,AUTOMATE,SORT_ORDER,LAST_UPDATED_DATE,LAST_UPDATED_BY,NOTES,MODULE_ID) values (9720,'Manage Actions','Function',9714,'Y',30,to_date('07-MAR-2017','DD-MON-RRRR'),'ATAF',null,9719);
Insert into ATAF.ATAF_TEST_SPEC (TEST_SPEC_ID,TEST_SPEC,TEST_TYPE,PROJECT_ID,AUTOMATE,SORT_ORDER,LAST_UPDATED_DATE,LAST_UPDATED_BY,NOTES,MODULE_ID) values (9724,'Manage Custom Items','Function',9714,'Y',50,to_date('07-MAR-2017','DD-MON-RRRR'),'ATAF',null,9723);
Insert into ATAF.ATAF_TEST_SPEC (TEST_SPEC_ID,TEST_SPEC,TEST_TYPE,PROJECT_ID,AUTOMATE,SORT_ORDER,LAST_UPDATED_DATE,LAST_UPDATED_BY,NOTES,MODULE_ID) values (9722,'Manage Test Data','Function',9714,'Y',40,to_date('07-MAR-2017','DD-MON-RRRR'),'ATAF',null,9721);
