REM INSERTING into ATAF.ATAF_PROJECT
SET DEFINE OFF;
Insert into ATAF.ATAF_PROJECT (PROJECT_ID,PROJECT_NAME,APPLICATION_ID,DOMAIN,LOGIN_PAGE,VERSION,LAST_UPDATED_DATE,LAST_UPDATED_BY,ACCESS_RESTRICTIONS,OWNER) values (9714,'ATAF Example',242,'https://apex7.revion.com/','1',null,to_date('07-MAR-2017','DD-MON-RRRR'),'ATAF',null,'ADMIN_USER');
