CREATE OR REPLACE FORCE VIEW  "ATAF_TEST_COND_FULL_V" ("DATA_ID", "TEST_COND_ID", "TEST_CASE_ID", "DATA_ITEM_ID", "ACTION_ID", "OUTCOME_PAGE_ID", "APEX_ITEM_ID", "SORT_ORDER", "PAGE_ID", "ROW_NUMBER", "LAST_UPDATED_DATE", "LAST_UPDATED_BY", "ROW_KEY", "ROW_VERSION_NUMBER", "DATA_ATTRIBUTE", "DATA_GROUP_ID", "TYPE", "OUTCOME_ID") AS 
  select
 DATA_ID,
 TEST_COND_ID,
 TEST_CASE_ID,
 DATA_ITEM_ID,
 ACTION_ID,
 OUTCOME_PAGE_ID,
 APEX_ITEM_ID,
 SORT_ORDER,
 PAGE_ID,
 ROW_NUMBER,
 LAST_UPDATED_DATE,
 LAST_UPDATED_BY,
 ROW_KEY,
 ROW_VERSION_NUMBER,
 /*+DATA_ATTRIBUTE*/ DATA_ATTRIBUTE,
 DATA_GROUP_ID,
 'Action' TYPE,
 OUTCOME_ID
 from ATAF_TEST_COND
UNION ALL
select
 DATA_ID,
 TEST_COND_ID,
 TEST_CASE_ID,
 DATA_ITEM_ID,
 OUTCOME_ID ACTION_ID,
 OUTCOME_PAGE_ID,
 APEX_ITEM_ID,
 sort_order + 0.5 sort_order,
 PAGE_ID,
 ROW_NUMBER,
 LAST_UPDATED_DATE,
 LAST_UPDATED_BY,
 ROW_KEY,
 ROW_VERSION_NUMBER,
 /*+DATA_ATTRIBUTE*/ DATA_ATTRIBUTE,
 DATA_GROUP_ID,
 'Outcome' TYPE,
  null
 from ATAF_TEST_COND
WHERE outcome_id IS NOT NULL
/