CREATE OR REPLACE FORCE VIEW "ATAF_FULL_TEST_DATA_CV" ("PROJECT_ID", "DATA_ID", "DATA_ITEM_ID", "ROW_NAME", "ROW_NUMBER", "ROW_KEY", "DATA_ITEM_VALUE", "TEST_DATA_ID", "ATTRIBUTE", "DATA_ITEM_NAME", "DATA_GROUP_ID") AS 
  select 
 -- Sticky Data --
 to_number(c001) PROJECT_ID,
 to_number(c002) DATA_ID,
 to_number(c003) DATA_ITEM_ID,
 c004 ROW_NAME,
 to_number(c005) ROW_NUMBER,
 c006 ROW_KEY,
 c007 DATA_ITEM_VALUE,
 to_number(c008) TEST_DATA_ID,
 to_number(c011) ATTRIBUTE,
 c012 DATA_ITEM_NAME,
 to_number(c013) DATA_GROUP_ID
 from APEX_COLLECTIONS
where collection_name = 'ATAF_DATA'
union all
select 
 PROJECT_ID,
 DATA_ID,
 DATA_ITEM_ID,
 ROW_NAME,
 ROW_NUMBER,
 ROW_KEY,
 DATA_ITEM_VALUE,
 TEST_DATA_ID,
 ATTRIBUTE,
 DATA_ITEM_NAME,
 DATA_GROUP_ID
 from ATAF_FULL_TEST_DATA_V
/