PROMPT 'Create Table Definitions'
---------------------------------
CREATE TABLE  "ATAF_PROJECT" 
   (	"PROJECT_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"APPLICATION_ID" NUMBER NOT NULL ENABLE, 
	"DOMAIN" VARCHAR2(256),  
	"VERSION" VARCHAR2(16), 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	"ACCESS_RESTRICTIONS" VARCHAR2(16), 
	"OWNER" VARCHAR2(32), 
	"TESTINGBOT_USERNAME" VARCHAR2(64), 
	"TESTINGBOT_PASSWORD" VARCHAR2(64),
	"TEST_LAB_SUITE_ID" NUMBER,
	 CONSTRAINT "PROJECT_PK" PRIMARY KEY ("PROJECT_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_ACTION" 
   (	"ACTION_ID" NUMBER, 
	"ITEM_TYPE" VARCHAR2(32) NOT NULL ENABLE, 
	"ACTION" VARCHAR2(64) NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"ROW_KEY" VARCHAR2(16) NOT NULL ENABLE, 
	"SCRIPT" VARCHAR2(256) NOT NULL ENABLE, 
	"DATA_YN" VARCHAR2(1), 
	"NOTES" VARCHAR2(4000), 
	"AND_WAIT" VARCHAR2(1), 
	 CONSTRAINT "ACTION_PK" PRIMARY KEY ("ACTION_ID") ENABLE, 
	 CONSTRAINT "ACTION_UK1" UNIQUE ("ITEM_TYPE", "ACTION") ENABLE
   )
/
CREATE TABLE  "ATAF_TEST_DATA" 
   (	"TEST_DATA_ID" NUMBER, 
	"DATA_NAME" VARCHAR2(64), 
	"PROJECT_ID" NUMBER, 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	"ROW_KEY" VARCHAR2(16) NOT NULL ENABLE, 
	"DEFAULT_DATA_GROUP_ID" NUMBER, 
	 CONSTRAINT "TEST_DATA_PK" PRIMARY KEY ("TEST_DATA_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_DATA_GROUPS" 
   (	"DATA_GROUP_ID" NUMBER, 
	"DATA_GROUP" VARCHAR2(64), 
	"TEST_DATA_ID" NUMBER, 
	 CONSTRAINT "ATAF_DATA_GROUPS_PK" PRIMARY KEY ("DATA_GROUP_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_DATA" 
   (	"DATA_ID" NUMBER, 
	"ATTRIBUTE_1" VARCHAR2(4000), 
	"ATTRIBUTE_2" VARCHAR2(4000), 
	"ATTRIBUTE_3" VARCHAR2(4000), 
	"ATTRIBUTE_4" VARCHAR2(4000), 
	"ATTRIBUTE_5" VARCHAR2(4000), 
	"ATTRIBUTE_6" VARCHAR2(4000), 
	"ATTRIBUTE_7" VARCHAR2(4000), 
	"ATTRIBUTE_8" VARCHAR2(4000), 
	"ATTRIBUTE_9" VARCHAR2(4000), 
	"ATTRIBUTE_10" VARCHAR2(4000), 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	"ROW_KEY" VARCHAR2(16) NOT NULL ENABLE, 
	"TEST_DATA_ID" NUMBER NOT NULL ENABLE, 
	"ROW_NAME" VARCHAR2(256) NOT NULL ENABLE, 
	"DATA_GROUP_ID" NUMBER, 
	"ATTRIBUTE_11" VARCHAR2(4000), 
	"ATTRIBUTE_12" VARCHAR2(4000), 
	"ATTRIBUTE_13" VARCHAR2(4000), 
	"ATTRIBUTE_14" VARCHAR2(4000), 
	"ATTRIBUTE_15" VARCHAR2(4000), 
	"ATTRIBUTE_16" VARCHAR2(4000), 
	"ATTRIBUTE_17" VARCHAR2(4000), 
	"ATTRIBUTE_18" VARCHAR2(4000), 
	"ATTRIBUTE_19" VARCHAR2(4000), 
	"ATTRIBUTE_20" VARCHAR2(4000), 
	 CONSTRAINT "DATA_PK" PRIMARY KEY ("DATA_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_DATA_ITEM" 
   (	"DATA_ITEM_ID" NUMBER, 
	"DATA_ITEM_NAME" VARCHAR2(64) NOT NULL ENABLE, 
	"DATA_ITEM_VALUE" VARCHAR2(4000), 
	"DATA_ATTRIBUTE" NUMBER NOT NULL ENABLE, 
	"TEST_DATA_ID" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	"ROW_KEY" VARCHAR2(16) NOT NULL ENABLE, 
	"DATA_FUNCTION" NUMBER, 
	"RANDOM_DATA" VARCHAR2(1), 
	"PARAMETER1" VARCHAR2(30), 
	"PARAMETER2" VARCHAR2(30), 
	 CONSTRAINT "DATA_ITEM_PK" PRIMARY KEY ("DATA_ITEM_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_ITEM" 
   (	"ITEM_ID" NUMBER, 
	"ITEM_NAME" VARCHAR2(64) NOT NULL ENABLE, 
	"ITEM_DOM_ID" VARCHAR2(64), 
	"PAGE_ID" NUMBER NOT NULL ENABLE, 
	"DISPLAY_SEQUENCE" NUMBER, 
	"ITEM_LABEL" VARCHAR2(128), 
	"APPLICATION_ID" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	"ITEM_TYPE" VARCHAR2(16) NOT NULL ENABLE, 
	"REGION_NAME" VARCHAR2(128), 
	 CONSTRAINT "ITEM_PK" PRIMARY KEY ("ITEM_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_MODULE" 
   (	"MODULE_ID" NUMBER, 
	"MODULE" VARCHAR2(128) NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"MODULE_REF_ID" NUMBER, 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "MODULE_PK" PRIMARY KEY ("MODULE_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_SELENIUM" 
   (	"SELENIUM_ID" NUMBER, 
	"SELENIUM_COMMAND" VARCHAR2(64), 
	"ACTION_ID" NUMBER, 
	"DATA_YN" VARCHAR2(1), 
	"LOCATION" VARCHAR2(64), 
	"TARGET" VARCHAR2(128), 
	"ITEM_ATTRIBUTE" VARCHAR2(16), 
	"ROW_KEY" VARCHAR2(16) NOT NULL ENABLE, 
	"SORT_ORDER" NUMBER, 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	"ROW_VERSION_NUMBER" NUMBER NOT NULL ENABLE, 
	"THEME_NUMBER" NUMBER, 
	 CONSTRAINT "SELENIUM_PK" PRIMARY KEY ("SELENIUM_ID", "THEME_NUMBER") ENABLE, 
	 CONSTRAINT "SELENIUM_UNI" UNIQUE ("ROW_KEY") ENABLE
   )
/
CREATE TABLE  "ATAF_TEST_CASE" 
   (	"TEST_CASE_ID" NUMBER, 
	"TEST_CASE" VARCHAR2(128) NOT NULL ENABLE, 
	"MODULE_ID" NUMBER NOT NULL ENABLE, 
	"PRIORITY" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(8) NOT NULL ENABLE, 
	"NOTES" VARCHAR2(4000), 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	"TEST_DATA_ID" NUMBER, 
	 CONSTRAINT "TEST_CASE_PK" PRIMARY KEY ("TEST_CASE_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_TEST_SPEC" 
   (	"TEST_SPEC_ID" NUMBER, 
	"TEST_SPEC" VARCHAR2(128) NOT NULL ENABLE, 
	"TEST_TYPE" VARCHAR2(32) NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"AUTOMATE" VARCHAR2(1), 
	"SORT_ORDER" NUMBER, 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	"NOTES" VARCHAR2(4000), 
	"MODULE_ID" NUMBER, 
	"TEST_LAB_TEST_ID" NUMBER,
	"CHANGE_FLAG" VARCHAR2(1),
	 CONSTRAINT "TEST_SPEC_PK" PRIMARY KEY ("TEST_SPEC_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_SPEC_CASE" 
   (	"SPEC_CASE_ID" NUMBER, 
	"TEST_SPEC_ID" NUMBER NOT NULL ENABLE, 
	"TEST_CASE_ID" NUMBER NOT NULL ENABLE, 
	"SORT_ORDER" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	"DATA_ID" NUMBER, 
	"DATA_GROUP_ID" NUMBER, 
	 CONSTRAINT "SPEC_CASE_PK" PRIMARY KEY ("SPEC_CASE_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_SYSTEM_PARAMETERS" 
   (	"NAME" VARCHAR2(1000) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000), 
	"VALUE" VARCHAR2(1000), 
	"VALUE_LARGE" CLOB, 
	"VALUE_RAW" RAW(64), 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE
   )
/
CREATE TABLE  "ATAF_TEST_CASE_IOT" 
   (	"TEST_CASE_ID" NUMBER, 
	"TEST_CASE_REF_ID" NUMBER, 
	 CONSTRAINT "TEST_CASE_IOT_PK" PRIMARY KEY ("TEST_CASE_ID", "TEST_CASE_REF_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_TEST_COND" 
   (	"TEST_COND_ID" NUMBER, 
	"TEST_CASE_ID" NUMBER NOT NULL ENABLE, 
	"DATA_ITEM_ID" NUMBER, 
	"ACTION_ID" NUMBER NOT NULL ENABLE, 
	"OUTCOME_ID" NUMBER, 
	"OUTCOME_PAGE_ID" VARCHAR2(32), 
	"APEX_ITEM_ID" NUMBER, 
	"SORT_ORDER" NUMBER, 
	"PAGE_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"ROW_NUMBER" VARCHAR2(16), 
	"LAST_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(32) NOT NULL ENABLE, 
	"ROW_KEY" VARCHAR2(16) NOT NULL ENABLE, 
	"ROW_VERSION_NUMBER" NUMBER NOT NULL ENABLE, 
	"DATA_ATTRIBUTE" NUMBER, 
	"DATA_ID" NUMBER, 
	"DATA_GROUP_ID" NUMBER,
	"NOT_IN_GROUP" VARCHAR2(1), 
	 CONSTRAINT "TEST_CONFIG_PK" PRIMARY KEY ("TEST_COND_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_USER_RESTRICTIONS" 
   (	"USER_RESTRICTIONS_ID" NUMBER, 
	"USERNAME" VARCHAR2(128) NOT NULL ENABLE, 
	"ACCESS_LEVEL" VARCHAR2(16) NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "USER_ACCESS_PK" PRIMARY KEY ("USER_RESTRICTIONS_ID") ENABLE
   )
/

CREATE TABLE  "ATAF_TEMP_MV" 
   (	"APPLICATION_ID" NUMBER, 
	"PAGE_ID" NUMBER, 
	"LABEL" VARCHAR2(4000), 
	"TYPE" VARCHAR2(255), 
	"DOM_ID" VARCHAR2(2000), 
	"NAME" VARCHAR2(4000), 
	"DISPLAY_SEQUENCE" NUMBER, 
	"ID" NUMBER, 
	"ELEMENT_TYPE" VARCHAR2(3), 
	"REGION_ID" VARCHAR2(51), 
	"REGION_NAME" VARCHAR2(255), 
	"DISPLAY_SEQUENCE1" NUMBER, 
	"DISPLAY_SEQUENCE2" NUMBER
   )
/

CREATE TABLE  "ATAF_TL_JOB" 
   (	"TL_JOB_ID" NUMBER, 
	"JOB_ID" NUMBER, 
	"SUCCESS" VARCHAR2(16), 
	"PROJECT_ID" NUMBER, 
	"TEST_SPEC_ID" NUMBER, 
	"SESSION_ID" VARCHAR2(64), 
	"ERRORS" VARCHAR2(4000), 
	"TEST_IDS" VARCHAR2(512), 
	"JSON" CLOB, 
	"JOB_DATE" DATE, 
	"RUN_SUCCESS" VARCHAR2(15), 
	"STATUS_CODE" VARCHAR2(16), 
	 CONSTRAINT "ATAF_TL_JOB_PK" PRIMARY KEY ("TL_JOB_ID") ENABLE
   )
/
CREATE TABLE  "ATAF_TL_TEST" 
   (	"TL_TEST_ID" NUMBER, 
	"JSON" CLOB, 
	"SUCCESS" VARCHAR2(16), 
	"TEST_LAB_TEST_ID" NUMBER, 
	"STATUS_CODE" VARCHAR2(16), 
	"TEST_DATE" DATE, 
	"TEST_SPEC_ID" NUMBER, 
	 CONSTRAINT "ATAF_TL_TEST_PK" PRIMARY KEY ("TL_TEST_ID") ENABLE
   )
/

PROMPT 'Update Table Definitions'
---------------------------------


PROMPT 'Add Constraints'
------------------------
ALTER TABLE  "ATAF_ACTION" ADD CONSTRAINT "ACTION_FK2" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "ATAF_PROJECT" ("PROJECT_ID") ENABLE
/
ALTER TABLE  "ATAF_DATA" ADD CONSTRAINT "ATAF_DATA_FK" FOREIGN KEY ("TEST_DATA_ID")
	  REFERENCES  "ATAF_TEST_DATA" ("TEST_DATA_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "ATAF_DATA" ADD CONSTRAINT "ATAF_DATA_FK1" FOREIGN KEY ("DATA_GROUP_ID")
	  REFERENCES  "ATAF_DATA_GROUPS" ("DATA_GROUP_ID") ENABLE
/
ALTER TABLE  "ATAF_DATA_GROUPS" ADD CONSTRAINT "ATAF_DATA_GROUPS_FK" FOREIGN KEY ("TEST_DATA_ID")
	  REFERENCES  "ATAF_TEST_DATA" ("TEST_DATA_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "ATAF_SPEC_CASE" ADD CONSTRAINT "ATAF_SPEC_CASE_FK1" FOREIGN KEY ("DATA_GROUP_ID")
	  REFERENCES  "ATAF_DATA_GROUPS" ("DATA_GROUP_ID") ENABLE
/
ALTER TABLE  "ATAF_TEST_COND" ADD CONSTRAINT "ATAF_TEST_COND_FK5" FOREIGN KEY ("DATA_GROUP_ID")
	  REFERENCES  "ATAF_DATA_GROUPS" ("DATA_GROUP_ID") ENABLE
/
ALTER TABLE  "ATAF_TEST_SPEC" ADD CONSTRAINT "ATAF_TEST_SPEC_CON" FOREIGN KEY ("MODULE_ID")
	  REFERENCES  "ATAF_MODULE" ("MODULE_ID") ENABLE
/
ALTER TABLE  "ATAF_DATA_ITEM" ADD CONSTRAINT "DATA_ITEM_FK" FOREIGN KEY ("TEST_DATA_ID")
	  REFERENCES  "ATAF_TEST_DATA" ("TEST_DATA_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "ATAF_MODULE" ADD CONSTRAINT "MODULE_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "ATAF_PROJECT" ("PROJECT_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "ATAF_MODULE" ADD CONSTRAINT "MODULE_FK2" FOREIGN KEY ("MODULE_REF_ID")
	  REFERENCES  "ATAF_MODULE" ("MODULE_ID") ON DELETE SET NULL ENABLE
/
ALTER TABLE  "ATAF_SELENIUM" ADD CONSTRAINT "SELENIUM_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES  "ATAF_ACTION" ("ACTION_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "ATAF_SPEC_CASE" ADD CONSTRAINT "SPEC_CASE_FK" FOREIGN KEY ("TEST_SPEC_ID")
	  REFERENCES  "ATAF_TEST_SPEC" ("TEST_SPEC_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "ATAF_SPEC_CASE" ADD CONSTRAINT "SPEC_CASE_FK2" FOREIGN KEY ("TEST_CASE_ID")
	  REFERENCES  "ATAF_TEST_CASE" ("TEST_CASE_ID") ENABLE
/
ALTER TABLE  "ATAF_TEST_CASE" ADD CONSTRAINT "TEST_CASE_CON_FK" FOREIGN KEY ("MODULE_ID")
	  REFERENCES  "ATAF_MODULE" ("MODULE_ID") ENABLE
/
ALTER TABLE  "ATAF_TEST_CASE" ADD CONSTRAINT "TEST_CASE_FK" FOREIGN KEY ("TEST_DATA_ID")
	  REFERENCES  "ATAF_TEST_DATA" ("TEST_DATA_ID") ENABLE
/
ALTER TABLE  "ATAF_TEST_CASE_IOT" ADD CONSTRAINT "TEST_CASE_IOT_FK" FOREIGN KEY ("TEST_CASE_ID")
	  REFERENCES  "ATAF_TEST_CASE" ("TEST_CASE_ID") ENABLE
/
ALTER TABLE  "ATAF_TEST_CASE_IOT" ADD CONSTRAINT "TEST_CASE_IOT_FK2" FOREIGN KEY ("TEST_CASE_REF_ID")
	  REFERENCES  "ATAF_TEST_CASE" ("TEST_CASE_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "ATAF_TEST_COND" ADD CONSTRAINT "TEST_CONFIG_FK1" FOREIGN KEY ("TEST_CASE_ID")
	  REFERENCES  "ATAF_TEST_CASE" ("TEST_CASE_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "ATAF_TEST_COND" ADD CONSTRAINT "TEST_CONFIG_FK2" FOREIGN KEY ("DATA_ITEM_ID")
	  REFERENCES  "ATAF_DATA_ITEM" ("DATA_ITEM_ID") ENABLE
/
ALTER TABLE  "ATAF_TEST_COND" ADD CONSTRAINT "TEST_CONFIG_FK3" FOREIGN KEY ("ACTION_ID")
	  REFERENCES  "ATAF_ACTION" ("ACTION_ID") ENABLE
/
ALTER TABLE  "ATAF_TEST_COND" ADD CONSTRAINT "TEST_CONFIG_FK4" FOREIGN KEY ("OUTCOME_ID")
	  REFERENCES  "ATAF_ACTION" ("ACTION_ID") ENABLE
/
ALTER TABLE  "ATAF_TEST_DATA" ADD CONSTRAINT "TEST_DATA_FK2" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "ATAF_PROJECT" ("PROJECT_ID") ENABLE
/
ALTER TABLE  "ATAF_TEST_DATA" ADD CONSTRAINT "TEST_DATA_FK3" FOREIGN KEY ("DEFAULT_DATA_GROUP_ID")
	  REFERENCES  "ATAF_DATA_GROUPS" ("DATA_GROUP_ID") ENABLE
/
ALTER TABLE  "ATAF_TEST_SPEC" ADD CONSTRAINT "TEST_SPEC_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "ATAF_PROJECT" ("PROJECT_ID") ENABLE
/
ALTER TABLE  "ATAF_USER_RESTRICTIONS" ADD CONSTRAINT "USER_ACCESS_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "ATAF_PROJECT" ("PROJECT_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "ATAF_TL_JOB" ADD CONSTRAINT "ATAF_TL_JOB_FK" FOREIGN KEY ("TEST_SPEC_ID")
	  REFERENCES  "ATAF_TEST_SPEC" ("TEST_SPEC_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "ATAF_TL_JOB" ADD CONSTRAINT "ATAF_TL_JOB_FK1" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "ATAF_PROJECT" ("PROJECT_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "ATAF_TL_TEST" ADD CONSTRAINT "ATAF_TL_TEST_FK" FOREIGN KEY ("TEST_SPEC_ID")
	  REFERENCES  "ATAF_TEST_SPEC" ("TEST_SPEC_ID") ON DELETE CASCADE ENABLE
/

PROMPT 'Create Indexes'
-----------------------
CREATE UNIQUE INDEX  "ATAF_SYSTEM_PARAMETERS_UK1" ON  "ATAF_SYSTEM_PARAMETERS" ("NAME")
/
PROMPT 'Create Sequences'
-------------------------
CREATE SEQUENCE   "ATAF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1000000 START WITH 8674 CACHE 20 NOORDER  NOCYCLE
/